export default {
    'Automóveis e Veículos': 1,
    'Bebês': 2,
    'Beleza e Saúde': 3,
    'Brinquedos': 4,
    'Cama, Mesa e Banho': 5,
    'Casa e Jardim': 6,
    'Casa Inteligente': 7,
    'CD, DVD e Blu-Ray': 8,
    'Celulares e Telefones': 9,
    'Câmeras e Filmadoras': 10,
    'Decoração de Natal': 11,
    'Eletrodomésticos': 12,
    'Eletroportáteis': 13,
    'Esporte e Lazer': 14,
    'Flores e Cestas': 15,
    'Games': 16,
    'Indústria e Comércio': 17,
    'Informática': 18,
    'Instrumentos Musicais': 19,
    'Joalheria': 20,
    'Livros e Revistas': 21,
    'Moda e Acessórios': 22,
    'Móveis e Decoração': 23,
    'Papelaria e Armarinho': 24,
    'Perfumaria e Maquiagem': 25,
    'Pet Shop': 26,
    'Produtos Importados': 27,
    'Sex Shop': 28,
    'Supermercado Online': 29,
    'Tabacaria': 30,
    'TV e Eletrônicos': 31,
    'Utilidades Domésticas': 32
}